services:
  storage-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: storage-api
    ports:
      - "5000:3000"
    environment:
      - PORT=3000
      - STORAGE_ROOT_PATH=/data/storage
    volumes:
      - ./storage-dev:/data/storage
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quit", "--tries=1", "--spider", "http://localhost:3000/health"]
